=== monarch-initiative/HpoCaseAnnotator/hpo-case-annotator-model/src/test/resources/models/first/somatic/cancer-mutation.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT mutation (publication,variantlist,disease,metadata?,targetgene?,biocurator,datecreated?,datemodified?)>
<!ELEMENT publication (authorlist,title,journal,year,volume,pages,pmid)>
<!ELEMENT authorlist (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT journal (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT volume (#PCDATA)>
<!ELEMENT pages (#PCDATA)>
<!ELEMENT pmid (#PCDATA)>
<!ELEMENT regulator (#PCDATA)>
<!ELEMENT variantlist (variant+)>
<!ELEMENT snippet (#PCDATA)>
<!ELEMENT pathomechanism (#PCDATA)>
<!ELEMENT variant (build,chromosome,pos,ref,alt,snippet,regulator,pathomechanism,validation)>
<!ELEMENT build (#PCDATA)>
<!ELEMENT chromosome (#PCDATA)>
<!ELEMENT pos (#PCDATA)>
<!ELEMENT ref (#PCDATA)>
<!ELEMENT alt (#PCDATA)>
<!ATTLIST variant genotype (heterozygous|homozygous) #REQUIRED>
<!ATTLIST variant class (promoter|enhancer|5UTR|3UTR|ICR|microRNAgene|RNP_RNAcomponent|LINC_RNA|coding|polyA_site|splicing) #REQUIRED>
<!ELEMENT validation (reporter|emsa|cosegregation|comparability|frequency|other)+>
<!ELEMENT reporter (#PCDATA)>
<!ATTLIST reporter direction (up|down) #REQUIRED>
<!ELEMENT emsa (entrezid,genesymbol)>
<!ELEMENT cosegregation (#PCDATA)>
<!ATTLIST cosegregation present (yes|no) #REQUIRED>
<!ELEMENT comparability (#PCDATA)>
<!ATTLIST comparability present (yes|no) #REQUIRED>
<!ELEMENT frequency (#PCDATA)>
<!ATTLIST frequency m CDATA #REQUIRED>
<!ATTLIST frequency n CDATA #REQUIRED>
<!ELEMENT other (#PCDATA)>
<!ATTLIST other direction (up|down|demonstrated) #REQUIRED>
<!ELEMENT disease (name,database,id)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT database (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT phenotypelist (phenotype*)>
<!ELEMENT phenotype (hpoid,hponame)>
<!ELEMENT hpoid (#PCDATA)>
<!ELEMENT hponame (#PCDATA)>
<!ELEMENT metadata (#PCDATA)>
<!ELEMENT targetgene (entrezid,genesymbol)>
<!ELEMENT entrezid (#PCDATA)>
<!ELEMENT genesymbol (#PCDATA)>

<!ELEMENT biocurator (#PCDATA)>
<!ELEMENT datecreated (#PCDATA)>
<!ELEMENT datemodified (#PCDATA)>

=== monarch-initiative/HpoCaseAnnotator/hpo-case-annotator-core/src/test/resources/models/first/somatic/Rachakonda-TERT-bladder-2013-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mutation PUBLIC "mutation" "cancer-mutation.dtd">
<mutation>
  <publication>
    <authorlist>Rachakonda PS, Hosen I, de Verdier PJ, Fallah M, Heidenreich B, Ryk C, Wiklund NP, Steineck G, Schadendorf D, Hemminki K, Kumar R</authorlist>
    <title>TERT promoter mutations in bladder cancer affect patient survival and disease recurrence through modification by a common polymorphism</title>
    <journal>Proc Natl Acad Sci U S A</journal>
    <year>2013</year>
    <volume>110(43)</volume>
    <pages>17426-31</pages>
    <pmid>24101484</pmid>
  </publication>
  <variantlist>
    <variant genotype="heterozygous" class="promoter">
      <build>37</build>
      <chromosome>5</chromosome>
      <pos>1295250</pos>
      <ref>G</ref>
      <alt>A</alt>
      <snippet>GG[G/A]AG</snippet>
      <regulator>TERT promoter</regulator>
      <pathomechanism>promoter|increased-transcription</pathomechanism>
      <validation>
        <reporter direction="up">150.00</reporter>
        <frequency m="38" n="327"/>
      </validation>
    </variant>
  </variantlist>
  <disease>
    <name>Bladder Carcinoma</name>
    <database>NCI</database>
    <id>C4912</id>
  </disease>
  <metadata>The authors investigated tumors from a well-characterized series of 327 patients with urothelial cell carcinoma of bladder. The somatic mutations, mainly at positions -124 and -146 bp from ATG start site that create binding motifs for E-twenty six/ternary complex factors (Ets/TCF), affected 65.4% of the tumors, with even distribution across different stages and grades. The authors' data showed that a common polymorphism rs2853669, within a preexisting Ets2 binding site in the TERT promoter, acts as a modifier of the effect of the mutations on survival and tumor recurrence. The patients with the mutations showed poor survival in the absence [hazard ratio (HR) 2.19, 95% confidence interval (CI) 1.02-4.70] but not in the presence (HR 0.42, 95% CI 0.18-1.01) of the variant allele of the polymorphism. The mutations in the absence of the variant allele were highly associated with the disease recurrence in patients with Tis, Ta, and T1 tumors (HR 1.85, 95% CI 1.11-3.08).</metadata>
  <targetgene>
    <entrezid>7015</entrezid>
    <genesymbol>TERT</genesymbol>
  </targetgene>
  <biocurator>HPO:mjabif</biocurator>
  <datecreated>1450708528517</datecreated>
  <datemodified>1450708528517</datemodified>
</mutation>

=== monarch-initiative/HpoCaseAnnotator/hpo-case-annotator-core/src/test/resources/models/first/somatic/George-TERT-2015.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mutation PUBLIC "mutation" "cancer-mutation.dtd">
<mutation>
  <publication>
    <authorlist>George JR, Henderson YC, Williams MD, Roberts DB, Hei H, Lai SY, Clayman GL</authorlist>
    <title>Association of TERT Promoter Mutation, But Not BRAF Mutation, With Increased Mortality in PTC</title>
    <journal>J Clin Endocrinol Metab</journal>
    <year>2015</year>
    <volume>100(12)</volume>
    <pages>E1550-9</pages>
    <pmid>26461266</pmid>
  </publication>
  <variantlist>
    <variant genotype="heterozygous" class="promoter">
      <build>37</build>
      <chromosome>5</chromosome>
      <pos>1295228</pos>
      <ref>G</ref>
      <alt>A</alt>
      <snippet>CGGA[G/A]GGG</snippet>
      <regulator>TERT promoter</regulator>
      <pathomechanism>promoter|increased-transcription</pathomechanism>
      <validation>
        <frequency m="77" n="42"/>
      </validation>
    </variant>
  </variantlist>
  <disease>
    <name>Thyroid Gland Papillary Carcinoma</name>
    <database>NCI</database>
    <id>C4035</id>
  </disease>
  <metadata>The authors' objective in this study was to determine the association of BRAF and TERT promoter gene alterations with recurrence and survival in a high-risk population. Genomic DNA was analyzed for the BRAF mutation from 256 persistent/recurrent papillary thyroid carcinoma samples (p/rPTC, 202 new, 54 previously reported). TERT promoter constructs were tested in PTC cell lines to determine their activities in these cells. The BRAF V600E mutation was identified in 235 of 256 (91.8%), TERT promoter mutation at -124 was detected in 77 of 242 (31.8%), and TERT promoter polymorphism at -245 was found in 113 of 242 (46.7%) of p/rPTC patients. A significant difference in survival was found in p/rPTC patients with the TERT promoter mutation, which also displayed increased activity in vitro as compared to the non-mutated promoter sequence. No association was noted between the BRAF mutation or TERT promoter polymorphism and recurrence or survival. A drawback of the authors' study could be the limited numbers of patients with non-mutated BRAF (21 of 256, 8.2%). The authors conclude that mutation in the TERT promoter, but not in BRAF, is associated with decreased survival in 19 (24.7%) p/rPTC patients who died of disease and in 38 (49.4%) p/rPTC patients who died at last contact. The presence or absence of the BRAF mutation and TERT promoter polymorphism, however, was not significantly correlated with survival.</metadata>
  <targetgene>
    <entrezid>7015</entrezid>
    <genesymbol>TERT</genesymbol>
  </targetgene>
  <biocurator>HPO:probinson</biocurator>
  <datecreated>1450016467143</datecreated>
  <datemodified>1450016467143</datemodified>
</mutation>

=== monarch-initiative/HpoCaseAnnotator/hpo-case-annotator-core/src/test/resources/models/first/somatic/Poulos-NDUFB9-2015.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mutation PUBLIC "mutation" "cancer-mutation.dtd">
<mutation>
  <publication>
    <authorlist>Poulos RC, Thoms JA, Shah A, Beck D, Pimanda JE, Wong JW</authorlist>
    <title>Systematic Screening of Promoter Regions Pinpoints Functional Cis-Regulatory Mutations in a Cutaneous Melanoma Genome</title>
    <journal>Mol Cancer Res</journal>
    <year>2015</year>
    <volume>13(8)</volume>
    <pages>1218-26</pages>
    <pmid>26082173</pmid>
  </publication>
  <variantlist>
    <variant genotype="heterozygous" class="5UTR">
      <build>37</build>
      <chromosome>8</chromosome>
      <pos>125551344</pos>
      <ref>C</ref>
      <alt>T</alt>
      <snippet>TCCGC[C/T]CTTCC</snippet>
      <regulator>NDUFB9 promoter</regulator>
      <pathomechanism>5UTR|reduced-transcription</pathomechanism>
      <validation>
        <reporter direction="down">80.00</reporter>
        <frequency m="19" n="432"/>
      </validation>
    </variant>
  </variantlist>
  <disease>
    <name>Cutaneous Melanoma</name>
    <database>NCI</database>
    <id>C3510</id>
  </disease>
  <metadata>The authors describe an NDUFB9 putative promoter mutation (chr8:125,551,344 C>T) within the 5'-untranslated region (UTR) of NDUFB9. The mutation was found in 19 of 432 samples with cutaneous melanoma. The protein encoded by NDUFB9 is part of both the mitochondrial dysfunction and oxidative phosphorylation (OXPHOS) key canonical pathways. In reporter assays, activity of the mutant NDUFB9 promoter decreased compared to wild-type. The mutation is predicted to abolish an SP1/Krueppel-like factor (KLF) binding motif and lies in a highly conserved region. The authors showed that he mutation co-occurs significantly in melanoma with nonsilent NF1 coding mutations.</metadata>
  <targetgene>
    <entrezid>4715</entrezid>
    <genesymbol>NDUFB9</genesymbol>
  </targetgene>
  <biocurator>HPO:probinson</biocurator>
  <datecreated>1447846454600</datecreated>
  <datemodified>1447846454600</datemodified>
</mutation>

=== monarch-initiative/HpoCaseAnnotator/hpo-case-annotator-model/src/test/resources/models/first/somatic/Scholz-TERT-2015-3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mutation PUBLIC "mutation" "cancer-mutation.dtd">
<mutation>
  <publication>
    <authorlist>Scholz SL, Thomasen H, Reis H, M�ller I, Darawsha R, M�ller B, Dekowski D, Sucker A, Schilling B, Schadendorf D, Steuhl KP, Paschen A, Westekemper H, Meller D, Griewank KG</authorlist>
    <title>Frequent TERT Promoter Mutations in Ocular Surface Squamous Neoplasia</title>
    <journal>Invest Ophthalmol Vis Sci</journal>
    <year>2015</year>
    <volume>56(10)</volume>
    <pages>5854-61</pages>
    <pmid>26348634</pmid>
  </publication>
  <variantlist>
    <variant genotype="heterozygous" class="promoter">
      <build>37</build>
      <chromosome>5</chromosome>
      <pos>1295250</pos>
      <ref>G</ref>
      <alt>A</alt>
      <snippet>GG[G/A]AG</snippet>
      <regulator>TERT promoter</regulator>
      <pathomechanism>promoter|increased-transcription</pathomechanism>
      <validation>
        <frequency m="12" n="48"/>
      </validation>
    </variant>
  </variantlist>
  <disease>
    <name>Conjunctival Squamous Cell Carcinoma</name>
    <database>NCI</database>
    <id>C4549</id>
  </disease>
  <metadata>One of the most common malignant tumors of the conjunctiva are epithelial-derived neoplasms, frequently termed ocular surface squamous neoplasias (OSSN), which include intraepithelial neoplasias (CIN) as well as fully invasive conjunctival squamous cell carcinoma (SCC).The authors analysed 48 ocular surface squamous neoplasia tumor samples (6 CIN and 42 SCC) for TERT mutations by Sanger sequencing. The authors identified TERT promoter mutations in 21 of 48 ocular surface squamous neoplasia samples (43.8%), including 4 in CIN and 17 in SCC. The mutations (note that the TERT gene is on the minus strand of chromosome 5, and the authors of this publication show the complementary bases) consisted of 8 cases of chr.5:1295228C>T, one case of chr.5:1295228_1295229CC>TT, 5 cases of chr.5:1295242_1295243CC>TT, and 12 cases of chr.5:1295250C>T mutations. All mutations were C>T or CC>TT alterations, demonstrating a UV-signature. TERT promoter mutations showed no statistically significant associations with clinicopathological parameters. Telomerase reverse transcriptase promoter mutations are found in almost half of ocular surface squamous neoplasias and have a mutation profile supporting UV induction as the major source of mutagenesis. They conclude conclude that UV induced TERT promoter mutations leading to aberrant overexpression of telomerase is a major pathogenetic factor in ocular surface squamous neoplasia. This entry covers twelve cases of 250C>T in the cohort.</metadata>
  <targetgene>
    <entrezid>7015</entrezid>
    <genesymbol>TERT</genesymbol>
  </targetgene>
  <biocurator>HPO:mjabif</biocurator>
  <datecreated>1450784047755</datecreated>
  <datemodified>1450784047755</datemodified>
</mutation>

=== monarch-initiative/HpoCaseAnnotator/hpo-case-annotator-model/src/test/resources/models/first/somatic/Denisova-DPH3-SCC-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mutation PUBLIC "mutation" "cancer-mutation.dtd">
<mutation>
  <publication>
    <authorlist>Denisova E, Heidenreich B, Nagore E, Rachakonda PS, Hosen I, Akrap I, Traves V, García-Casado Z, López-Guerrero JA, Requena C, Sanmartin O, Serra-Guillén C, Llombart B, Guillén C, Ferrando J, Gimeno E, Nordheim A, Hemminki K, Kumar R</authorlist>
    <title>Frequent DPH3 promoter mutations in skin cancers</title>
    <journal>Oncotarget</journal>
    <year>2015</year>
    <volume>[Epub ahead of print]</volume>
    <pages>null</pages>
    <pmid>26416425</pmid>
  </publication>
  <variantlist>
    <variant genotype="heterozygous" class="promoter">
      <build>37</build>
      <chromosome>3</chromosome>
      <pos>16306504</pos>
      <ref>C</ref>
      <alt>T</alt>
      <snippet>TAGC[C/T]CTTCCGG</snippet>
      <regulator>DPH3 promoter</regulator>
      <pathomechanism>promoter|unknown</pathomechanism>
      <validation>
        <frequency m="3" n="31"/>
      </validation>
    </variant>
  </variantlist>
  <disease>
    <name>Skin Squamous Cell Carcinoma</name>
    <database>NCI</database>
    <id>C4819</id>
  </disease>
  <metadata>The authors performed exome sequencing of 21 melanomas, and report frequent somatic mutations in skin cancers in a bidirectional promoter of diphthamide biosynthesis 3 (DPH3) and oxidoreductase NAD-binding domain containing 1 (OXNAD1) genes. The UV-signature mutations occurred at sites adjacent and within a binding motif for E-twenty six/ternary complex factors (Ets/TCF), at -8 and -9 bp from DPH3 transcription start site. Follow up screening of 586 different skin lesions showed that the DPH3 promoter mutations were present in melanocytic nevi (2/114; 2%), melanoma (30/304; 10%), basal cell carcinoma of skin (BCC; 57/137; 42%) and squamous cell carcinoma of skin (SCC; 12/31; 39%). Reporter assays carried out in one melanoma cell line for DPH3 and OXNAD1 orientations showed statistically significant increased promoter activity due to -8/-9CC > TT tandem mutations; although, no effect of the mutations on DPH3 and OXNAD1 transcription in tumors was observed. Here, a variant at hg19 coordinate chr3:16,306,504 that is 8 bp upstream of DPH3 RefSeq transcription start site (TSS), hence named -8C>T, is described.</metadata>
  <targetgene>
    <entrezid>285381</entrezid>
    <genesymbol>DPH3</genesymbol>
  </targetgene>
  <biocurator>HPO:probinson</biocurator>
  <datecreated>1447492789014</datecreated>
  <datemodified>1447492789014</datemodified>
</mutation>
